remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins

title: Jose Rivera
logo: assets/img/profile picture.jpg
description: This is a personal portfolio intended to showcase my projects to land a job in Data Science

show_downloads: false

